from app.tasks.check_login_status import run_check_login_status
from app.tasks.follow import run_follow_action
from app.tasks.get_post_url import run_get_post_url
from app.tasks.like import run_like_action
from app.tasks.posting import run_posting
from app.tasks.save_auth_state import run_save_auth_state
from app.tasks.backup_db import run_backup_database
from app.tasks.restore_auth_state import run_restore_auth_state
from app.tasks.commit_stale_actions import run_commit_stale_actions
from app.tasks.manual_test import run_manual_test